### ISSUE TITLE
Add documentation on how to use these in your pipeline

### ISSUE THREAD

**Issue by brandonmcclure** [brandonmcclure/Az-Devops-Pipeline-Templates#1]
Basically, make a github service connection named `githubServiceConnection` and then add a resources node to your yaml like:

```
resources:
  repositories:
      - repository: templates
        type: github
        name: brandonmcclure/Community-Az-Devops-Pipeline-Templates
        endpoint: githubServiceConnection
        trigger:
          - main
      - repository: self
```
